### ISSUE TITLE
pin_names.ino example - Problems compiling with arduino ide

### ISSUE THREAD

**Issue by Schlunze** [sigmdel/xiao_esp32c3_sketches#1]
Hello, i tried your example and have problems compiling pin_names.ino
First thing, the sketch dont compile in Arduino IDE. This gives following error:

`/home/linux_user/.var/app/cc.arduino.IDE2/cache/.arduinoIDE-unsaved2023419-31-fydlgl.4ggyk/sketch_may19a/sketch_may19a.ino: In function 'void setup()':
/home/linux_user/.var/app/cc.arduino.IDE2/cache/.arduinoIDE-unsaved2023419-31-fydlgl.4ggyk/sketch_may19a/sketch_may19a.ino:44:36: error: expected ';' before '}' token
   Serial.println("Setup completed")
                                    ^
                                    ;
 }
 ~                                   

exit status 1

Compilation error: expected ';' before '}' token`

Solution for this: line 44   Serial.println("Setup completed") ;

with platformio & arduino i got the following error:

`/home/linux_user/.arduino15/packages/esp32/tools/riscv32-esp-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: /home/oliver/.var/app/cc.arduino.IDE2/cache/arduino/cores/2bc666fc1425482704a1f7e05f40325e/core.a(main.cpp.o): in function `loopTask(void*)':
/home/linux_user/.arduino15/packages/esp32/hardware/esp32/2.0.9/cores/esp32/main.cpp:47: undefined reference to `setup()'
/home/linux_user/.arduino15/packages/esp32/tools/riscv32-esp-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: /home/oliver/.arduino15/packages/esp32/hardware/esp32/2.0.9/cores/esp32/main.cpp:47: undefined reference to `loop()'
collect2: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1`

**Comment by sigmdel** [comment]
Added the missing ";". 
Thank you for letting me know.
